
server:
  port: 80
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true
  application:
    name: indiev-gateway

